# .github/workflows/release.yml
name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-gnu

      - name: Install cross
        uses: taiki-e/install-action@cross

      - name: Build
        run: cross build --target x86_64-pc-windows-gnu --release --bins --lib

      - name: Prepare archives
        run: |
          cp target/x86_64-pc-windows-gnu/release/path_server.exe .
          cp target/x86_64-pc-windows-gnu/release/path_server_lib.dll .
          
          zip -r path_server.zip path_server.exe www/
          zip -r path_server_lib.zip path_server_lib.dll www/ui.html

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            path_server.zip
            path_server_lib.zip