# .github/workflows/release.yml
name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release --bins --lib

      - name: Prepare archives
        shell: pwsh
        run: |
          Copy-Item target\release\path_server.exe .
          Copy-Item target\release\path_server_lib.dll .
          
          Compress-Archive -Path path_server.exe, www -DestinationPath path_server.zip
          Compress-Archive -Path path_server_lib.dll, www\ui.html -DestinationPath path_server_lib.zip

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            path_server.zip
            path_server_lib.zip
            